# SPDX-FileCopyrightText: 2016 The Glucometer Protocols Authors
#
# SPDX-License-Identifier: MIT

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/fsfe/reuse-tool
    rev: v0.12.1
    hooks:
    - id: reuse
